[package]
name = "alm-core"
version = "0.1.0"
edition = "2024"

[dependencies]
alm-time = { path = "../alm-time" }

chrono = { version = "0.4.45", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
uuid = { version = "1.26.1", features = ["serde", "v4"] }
